name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          JWT_SECRET: "ci-jwt-secret-testing-string-key-12345"
          ENCRYPTION_KEY: "ISbUewgsbMaz0PyQ+fcuZenYq6wyfkzxghPPZP6cflwE="
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/devtrack_test"

      - name: Run unit & integration tests
        run: npm run test
        env:
          JWT_SECRET: "ci-jwt-secret-testing-string-key-12345"
          ENCRYPTION_KEY: "ISbUewgsbMaz0PyQ+fcuZenYq6wyfkzxghPPZP6cflwE="
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/devtrack_test"
